// Scenario definitions for the simulation
export const SCENARIOS = {
  status_quo: {
    capex_base: 70,
    capex_growth: 6,
    lambda_H: 35,
    supply_level: 50,
    supply_growth: 2,
    revenue_mult: 42,
    compute_intensity: 60,
    device_mode: 0,
    edge_progress: 0,
    sovereign_rate: 40,
    sov_horizon: 20,
    investor_val: 75,
    inv_risk: 50,
    regulator_stance: 0,
    grid_growth: 2.0,
    label: 'Status Quo — Nash Equilibrium baseline. All players locked in dominant strategies.'
  },
  supply_surge: {
    capex_base: 70,
    capex_growth: 6,
    lambda_H: 35,
    supply_level: 90,
    supply_growth: 8,
    revenue_mult: 42,
    compute_intensity: 60,
    device_mode: 0,
    edge_progress: 0,
    sovereign_rate: 40,
    sov_horizon: 20,
    investor_val: 75,
    inv_risk: 50,
    regulator_stance: 0,
    grid_growth: 2.0,
    label: 'Supply Surge — Nvidia/TSMC dramatically expands capacity. T* delayed, GPU prices fall.'
  },
  reg_freeze: {
    capex_base: 70,
    capex_growth: 6,
    lambda_H: 35,
    supply_level: 50,
    supply_growth: 2,
    revenue_mult: 42,
    compute_intensity: 60,
    device_mode: 0,
    edge_progress: 0,
    sovereign_rate: 40,
    sov_horizon: 20,
    investor_val: 75,
    inv_risk: 50,
    regulator_stance: 2,
    grid_growth: 0,
    label: 'Regulatory Freeze — Grid expansion halted. Ω stagnates. T* dramatically accelerated.'
  },
  inv_pullback: {
    capex_base: 70,
    capex_growth: 6,
    lambda_H: 35,
    supply_level: 50,
    supply_growth: 2,
    revenue_mult: 20,
    compute_intensity: 40,
    device_mode: 0,
    edge_progress: 0,
    sovereign_rate: 40,
    sov_horizon: 20,
    investor_val: 25,
    inv_risk: 20,
    regulator_stance: 0,
    grid_growth: 2.0,
    label: 'Investor Pullback — Confidence falls, valuation multiples compress. Moving denominator collapses.'
  },
  sovereign_surge: {
    capex_base: 70,
    capex_growth: 6,
    lambda_H: 35,
    supply_level: 50,
    supply_growth: 2,
    revenue_mult: 42,
    compute_intensity: 60,
    device_mode: 0,
    edge_progress: 0,
    sovereign_rate: 90,
    sov_horizon: 5,
    investor_val: 75,
    inv_risk: 50,
    regulator_stance: 0,
    grid_growth: 2.0,
    label: 'Sovereign Surge — Nations aggressively stockpile compute. Φ spikes, T* drastically accelerated.'
  },
};

export const getDefaultParams = () => ({ ...SCENARIOS.status_quo });
